### ISSUE TITLE
No response in my iPhone

### ISSUE THREAD

**Issue by leoliupei** [marcoraddatz/homebridge-docker#14]
I download the latest version of the image, Run with you step by step. But nothing happens on my iPhone

here goes the config.json

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CC:22:3D:E3:CE:72",
>         "port": 51826,
>         "pin": "031-45-154"
>     },
>     "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
>     "accessories": [
>     ]
> }

and the install.sh is empty

logs in the docker's terminal

> *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.                                                                                   
> *** WARNING *** Please fix your application to use the native API of Avahi!                                                                                                 
> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>                                                                             
> *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.  
> *** WARNING *** Please fix your application to use the native API of Avahi!                                                                                                 
> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>                                                        
> [4/18/2017, 6:35:39 PM] No plugins found. See the README for information on installing plugins.                                                                             
> [4/18/2017, 6:35:39 PM] Loaded config.json with 0 accessories and 0 platforms.                                                                                              
> [4/18/2017, 6:35:39 PM] ---                                                                                                                                                 
> [4/18/2017, 6:35:39 PM] Loading 0 accessories...                                                                                                                            
> Scan this code with your HomeKit App on your iOS device to pair with Homebridge:                                                                                            
>                                                                                                                                                                             
>     ┌────────────┐                                                                                                                                                          
>     │ 031-45-154 │                                                                                                                                                          
>     └────────────┘                                                                                                                                                          
>                                                                                                                                                                             
> [4/18/2017, 6:35:39 PM] Homebridge is running on port 51826.

everything seems well but I can't find the bridge in my iPhone, and find it immediate by Mac homebridge server.

run docker ps
![default](https://cloud.githubusercontent.com/assets/4571916/25147561/84bca6d8-24aa-11e7-8609-166323c17457.jpeg)

try many times... T_T

**Comment by tehoro** [comment]
I've found that it sometimes helps to change the username of the bridge - i.e., try changing some of the digits in "CC:22:3D:E3:CE:72".

**Comment by marcoraddatz** [comment]
@tehoro is right. Homebridge is running as it should, but there might be conflicts due to multiple Homebridge instances from testing.

**Comment by leoliupei** [comment]
I changed the username AKA mac address to many other strings, still not work. :(

**Comment by tehoro** [comment]
Other things to try are deleting any previous created **accessories** folder and **persist** folder.

**Comment by marcoraddatz** [comment]
Also, make sure the ports are available and don't get blocked by your firewall.
