### ISSUE TITLE
Cannot run on Raspberry Pi?

### ISSUE THREAD

**Issue by crhan** [marcoraddatz/homebridge-docker#16]
> standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by marcoraddatz** [comment]
Which version are you using? Have you made sure the linked paths are correct? (https://github.com/marcoraddatz/homebridge-docker/blob/master/homebridge.sh#L25)

**Comment by crhan** [comment]
Problem fixed by using rpi image. And there are some tricky teches can make docker hub to build arm image from x86 hosts

My fork: https://github.com/crhan/homebridge-docker/tree/rpi
my hub image: [crhan/rpi-homebridge:rpi-latest](https://hub.docker.com/r/crhan/rpi-homebridge/)
reference: https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
