### ISSUE TITLE
Plugins are not installing

### ISSUE THREAD

**Issue by Crady123** [marcoraddatz/homebridge-docker#18]
Hi,

I would like to install 2 plugins:
homebridge-homematic and homebridge-netatmo

my install.sh:
`npm install -g homebridge-homematic
npm install -g homebridge-netatmo`

both plugins are not installed and so homebridge does not find and plugins and shuts down itself.

what to do?

Error:

[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Cannot read property 'path' of null
stdout
13:42:57

**Comment by Crady123** [comment]
according to this:

https://github.com/npm/npm/issues/11515

there might be a typo or a language... you developed in english - I am using German language,,,

**Comment by marcoraddatz** [comment]
If it's written in one line, it must be `npm install -g homebridge-homematic && npm install -g homebridge-netatmo`.

However, this is not related to Homebridge itself, but to bash/plugins instead.

**Comment by Crady123** [comment]
Thank you for your answer. 
Suddenly it worked... not sure what happened - but I think there might have been a problem with the install.sh....

I just createt a new file, did a copy&paste from your manual. Perhaps some bad but invisible characters came into my first install.sh?

I have editied my install.sh unisg the text editor from synology in the filestation later and then it worked.

**Comment by marcoraddatz** [comment]
Glad to hear that!
