### ISSUE TITLE
How can I change it to use the latest homebridge release?

### ISSUE THREAD

**Issue by benzman81** [marcoraddatz/homebridge-docker#2]
Starting the docker shows v0.4.6, but latest is v0.4.16.

Is it possible to change it on my side, if not, could you update it?

**Comment by marcoraddatz** [comment]
It should be possible to update Homebridge within the `install.sh` script, which is executed after each start. However, I might add an auto-update next week (I cannot test and deploy code right now) and update the container.

**Comment by benzman81** [comment]
Thx for the fast answer, I guess I'll wait for you update.

**Comment by DaveHamilton** [comment]
What command would it be to update homebridge inside install.sh? I tried last night by adding `npm update -g homebridge` to the start and it resulted in an un-runnable copy of homebridge. Had to nuke and pave back to a fresh container. ;)

**Comment by marcoraddatz** [comment]
Yes, same happened to me. That's also the reason, why I wanted to avoid untested commits. ;) However, I'm now back at home and will update the image tomorrow, so that homebridge:latest will use 0.4.16.

**Comment by marcoraddatz** [comment]
A few minutes ago, I pushed all changes to the develop branch. 0.4.16 is now pre-installed and on container startup, Homebridge _should_ be updated automatically. Because of the crashes @DaveHamilton and I had, I didn't push it to `latest` yet and want to wait until Homebridge > v0.4.16 gets released.

However, feel free to test it via `homebridge:develop`.

**Comment by nota3k** [comment]
I'm testing out the develop branch on my QNAP via Container Station, no dice yet. Looks like it's not starting up fully. Here's what's showing in the Console:
```
Logged in as:                                                                                                                                           
root                                                                                                                                                    
/root/.homebridge/.env not found.                                                                                                                       
Default env variables will be used.                                                                                                                     
Updating Homebridge.                                                                                                                                    
/root/.homebridge/package.json not found.                                                                                                               
Installing plugins from /root/.homebridge/install.sh.                                                                                                   
/usr/lib                                                                                                                                                
`-- homebridge-philipshue@0.0.3 
```

Here's the command I'm running when I'm ssh'd in my NAS. 

`docker run -d --name HomeBridge --restart=always --net=host -p 51826:51826 -v /share/docker/homebridge:/root/.homebridge marcoraddatz/homebridge:develop`

Files are located in `/share/docker/homebridge`

**install.sh**
```
#!/bin/bash
npm install -g homebridge-philipshue
```

**config.json**
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154”
	}
}
```


Works fine on the latest branch, any ideas? Thanks for all your work on this.

**Comment by marcoraddatz** [comment]
Just to make sure, I understood you right: It doesn't start via develop, but on latest all is fine? From what I see, I cannot say what's wrong. 

Could you try to install the Hue plugin via `npm install -g https://github.com/thkl/homebridge-philipshue`? I had some trouble with the plugin when I wanted to fetch the latest version via NPM.

**Comment by benzman81** [comment]
I had the same issue. Only worked as I added the .env file with its content.

**Comment by benzman81** [comment]
Using latest version now, so original issue can be closed.

**Comment by marcoraddatz** [comment]
Thank you. My fault, pushed a new version that should fix the problem.

**Comment by benzman81** [comment]
Using latest version and it is working.

**Comment by DaveHamilton** [comment]
I have `develop` installed on my Synology DiskStation 1815+ and working just fine. No issues whatsoever. Thanks, @marcoraddatz!

**Comment by nota3k** [comment]
Works now, thanks @marcoraddatz! Up and running on my QNAP TS-251+.
