### ISSUE TITLE
FFmpeg support

### ISSUE THREAD

**Issue by DanielWeeber** [marcoraddatz/homebridge-docker#20]
Hey, great plugin. Love your work. Working flawless for me!

How can I add ffmpeg to the package? I want to control a camera via homebridge and this needs ffmpeg installed.

**Comment by marcoraddatz** [comment]
Hey, nice to hear. I've updated the readme, since this gets requested a lot: https://github.com/marcoraddatz/homebridge-docker/tree/develop#installsh

**Comment by DanielWeeber** [comment]
Unfortunately this is not a valid package.
(for my docker container on my Synology; debian)

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate

It should be apt-get install libav-tools -y
:)

**Comment by DanielWeeber** [comment]
Checked again, libav-tools does not work, but this in install.sh does:

```
echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list
apt-get update
apt-get -y install ffmpeg
```
Copied from:
https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/75#issuecomment-299633284

**Comment by marcoraddatz** [comment]
Thanks for the feedback! I updated the readme with the workaround.
