### ISSUE TITLE
homebridge -I mode

### ISSUE THREAD

**Issue by DanielWeeber** [marcoraddatz/homebridge-docker#21]
Hey,

I need to run homebridge with -I flag for accessing the HTTP API of Homebridge.
run.sh revealed, that this is not possible. Can you add a new flag? 

"production-http" or something like that, which runs "homebridge -I ;;"?

Greets

**Comment by marcoraddatz** [comment]
What exactly does this command? (Sorry, cannot check it on my own right now)

**Comment by DanielWeeber** [comment]
run the homebridge in an unsecure mode, meaning the HTTP Api is enabled. So I can access the protocol via HTTP requests. You can get the status of all characteristics/platforms (and set it!) via HTTP.
Maybe call it "insecure" instead of "production-http" so it is clear.

**Comment by marcoraddatz** [comment]
Would it make sense to also include it for "development" (`homebridge -I -P $plugin_folder ;;`)? What do you think?

**Comment by DanielWeeber** [comment]
yeah, why not. The execution itself stays the same, just the HTTP Api is enabled in background. Just tested it.
Or add a new flag "development-insecure"?

I can also create a PR if we decided what to do, if you like.

**Comment by marcoraddatz** [comment]
What do you think about two new flags? `production_insecure` and `development_insecure`?

**Comment by DanielWeeber** [comment]
Would be perfect!

See PR #24

**Comment by marcoraddatz** [comment]
Looks good! Thanks! Shall we use "development_insecure" or "development-insecure"? Accidently wrote "development_insecure" above but meant "development-insecure", which might be more obvious. 🙄 What do you prefer?

**Comment by marcoraddatz** [comment]
And another small thing: Current development_insecure is the debug mode. Shall we add this as a third option?

**Comment by DanielWeeber** [comment]
Like this? (See PR)
Sounds good to me.

**Comment by marcoraddatz** [comment]
Looks awesome!
