### ISSUE TITLE
Upgrade to Debian stretch

### ISSUE THREAD

**Issue by nicx** [marcoraddatz/homebridge-docker#22]
Currently jessie is used, but for some addons I need the actual stabel veriosn of Debian "stretch".
Any plans to upgrade?

**Comment by davebv** [comment]
I just submitted a pull request. You might review it: #23

**Comment by marcoraddatz** [comment]
Thanks for the PR. Will check it out asap – am currently not at home so cannot test it.

**Comment by davebv** [comment]
Thanks!

**Comment by nicx** [comment]
still waiting for this, I need the current stable branch of debian stretch instead of the outdated jessie :) will it be possible in future? currently I need a own fork for this :(

**Comment by marcoraddatz** [comment]
It will – but sadly I cannot test it until October. We can merge it and I can create the branches, but must rely on your feedback.

**Comment by nicx** [comment]
let the tests be done by the community, me included :)

**Comment by davebv** [comment]
I tested this myself in QNAP and did not find any issues. Newer debian version and ffmpeg works as expected.

**Comment by marcoraddatz** [comment]
Updates have been pushed to master and develop branch and should be available soon via Docker Hub. Please test changes, since I cannot right now 😞
