### ISSUE TITLE
works incorrectly after a while

### ISSUE THREAD

**Issue by zhooley** [marcoraddatz/homebridge-docker#26]
Hi!

It works fine, but after a while I see my accessories state corectly if I turn the lamps manually on or off, but if I turn the lights off and on from the phone, their status changes only on the phone, the real device does not turn on or off.

After homebridge restart it works again for a while.

Any suggestion?

Thanks

**Comment by marcoraddatz** [comment]
What plugins are you using?

**Comment by zhooley** [comment]
I used homebridge-loxone-ws plugin.

With IOS 11 it looks like it does not work.

**Comment by marcoraddatz** [comment]
Make sure Bonjour is running correctly and you're not using IPv6. Does it help? (Got no problems with iOS 11)
