### ISSUE TITLE
Problem running docker version 4.0

### ISSUE THREAD

**Issue by milanmitosinka** [marcoraddatz/homebridge-docker#28]
Hello,

I have problem running docker version 4.0.  
<img width="780" alt="screenshot" src="https://user-images.githubusercontent.com/7058403/30714438-0e898a92-9f13-11e7-8435-270ea6d72853.png">
I have one old "latest" which is working fine and all just start.
If I want to start 4.0 package with same settings and same plugins and all instead of older one. 

In image section of docker I have this:
one container with latest - this one works for me (782 MB)
one container with 3.1 - this one stops after 1 min.(784 MB)
one container with 4.0 - this stops after 1 min. (1 GB) 

do you have hint why ? 
I believe I need to use some new version due to iOS 11 coz current version is not reachable on my phone.

Any hints ? Is there any difference between install.sh and directory location ? See mine. 3.0 works fine.
I have just 3 plugins.

I found in the log this: 
This is related to npm not being able to find a file. Q: was there change in this between 3.0 and 3.1 or 4.0 ? 
and end error: Error: The requested platform 'Nest' was not registered by any plugin.

<img width="452" alt="screenshot" src="https://user-images.githubusercontent.com/7058403/30714901-c9df77e2-9f14-11e7-8557-6afae80e284c.png">

thank you !

Milan

**Comment by marcoraddatz** [comment]
Since version 2.1 there's not been any major changes to the `install.sh`, so all should be fine. The one minute stop seems to be Nest or another plugin not working correctly and crashing Homebridge. I guess your current container was version 2.1 or 2.0.x, where Homebrige < 0.4.16 was pre-installed. The newer version do an auto-update of Homebridge, so the Nest version might be incompatible with an update.

**Comment by milanmitosinka** [comment]
Hi,

I cuttet out nest of install.sh and confing as well. It is possible that all of my plugins are outdated ?
Here is log after start:


On 21 Sep 2017, at 22:01, Marco Raddatz <notifications@github.com> wrote:

Since version 2.1 there's not been any major changes to the install.sh, so all should be fine. The one minute stop seems to be Nest or another plugin not working correctly and crashing Homebridge. I guess your current container was version 2.1 or 2.0.x, where Homebrige < 0.4.16 was pre-installed. The newer version do an auto-update of Homebridge, so the Nest version might be incompatible with an update.

**Comment by milanmitosinka** [comment]
[marcoraddatz-homebridge2-2.pdf](https://github.com/marcoraddatz/homebridge-docker/files/1322589/marcoraddatz-homebridge2-2.pdf)

**Comment by marcoraddatz** [comment]
Sorry to say: But yes, I think the other plugins are also not working correctly. This error was thrown by `homebridge-tahoma`.

**Comment by milanmitosinka** [comment]
OK. I will try to find newest plugins for 4.0 version and keep you posted. Is there anything that has changed ? I put plugin into folder /docker/homebridge with homebridge-xxxx
Do you have some relatively good source of plugins ? 

Is 4.0 workimg with iOS 11 HomeKit ? I would not uprgade unless I would have to due to iOS 11.

Ty,
M.
On 21 Sep 2017, at 22:50, Marco Raddatz <notifications@github.com> wrote:

Sorry to say: But yes, I think the other plugins are also not working correctly. This error was thrown by homebridge-tahoma.

**Comment by marcoraddatz** [comment]
Maybe the plugins have changed configs or aren't compatible with newest Homebridge. This container (v4.0) is compatible with iOS 11, as long as the used Homebridge version is up to date.

Btw. you don't need to put the plugins into the folder, as long as you're not developing your own plugin. Try to install them via `install.sh`: https://github.com/marcoraddatz/homebridge-docker/blob/master/samples/install.sh
