### ISSUE TITLE
Add config to enable debug

### ISSUE THREAD

**Issue by benzman81** [marcoraddatz/homebridge-docker#3]
Would be nice to be able to turn on debug mode via configuration.

**Comment by marcoraddatz** [comment]
I think the best way would be to use Docker variables to set an environment? Or do you have another solution in mind?

**Comment by benzman81** [comment]
I have no experence in configuring docker images, just know how to run and stop :-)) any solution would be great ;-)

**Comment by marcoraddatz** [comment]
Please have a look at the [develop branch](https://github.com/marcoraddatz/homebridge-docker/tree/develop#plugin-development). It's now possible to set an environment via `.env` file. Does this work for you?

**Comment by benzman81** [comment]
without the .env file homebridge didnt start

with the .env file with `HOMEBRIDGE_ENV=debug` it does not seem to start in debug mode

**Comment by benzman81** [comment]
In a sample script it aways evaluates to the default start.
If I change my sample to the following the correct start will be triggered:

`# Start Homebridge`
`if [ -z ${HOMEBRIDGE_ENV+x} ]`
`then`
`    homebridge`
`else`
`    case "$HOMEBRIDGE_ENV" in`
`        "debug" )`
`            DEBUG=* homebridge -D -P $plugin_folder ;;`
`        "development" )`
`            homebridge -P $plugin_folder ;;`
`        "production" )`
`            homebridge ;;`
`    esac`
`fi`

**Comment by marcoraddatz** [comment]
Many thanks. I changed the order and didn't updated the option from "-z" to "-n". The debug mode should now start again.

```
# Start Homebridge
if [ -n "$HOMEBRIDGE_ENV" ]
then
    case "$HOMEBRIDGE_ENV" in
        "debug" )
            DEBUG=* homebridge -D -P $plugin_folder ;;
        "development" )
            homebridge -P $plugin_folder ;;
        "production" )
            homebridge ;;
    esac
else
    homebridge
fi
```

From what I see, our code should work the same way... ;)

**Comment by benzman81** [comment]
Yes, now its starting in debug mode. Thx.
