### ISSUE TITLE
ip camera stream doesn't work

### ISSUE THREAD

**Issue by Diederik98** [marcoraddatz/homebridge-docker#30]
Hi, 

Thanks a lot for your software!
I successfully installed ffmpeg and homebridge, but I can't get the streaming in HomeKit working.
I checked if ffmpeg was installed by executing ffmpeg.
The snapshot works great. Here's my config:
{
    "bridge": {
        "name": "Homebridge Synology",
        "username": "AC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
    ],

    "platforms": [{
  "platform": "Camera-IP",
  "cameras": [
    {
      "name": "Camera",
      "videoConfig": {
      	"source": "-re -i http://192.168.0.130:8081",
      	"stillImageSource": "-i http://192.168.0.130/picture/1/current/",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 25
      }
    }
  ]
}
    ]
}
In my log I can see:

 -re -i http://192.168.0.130:8081 -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 4pXKX4bLVc0+SbPl8bUTDv8JW6+mqyEMZwJI4z/c  srtp://192.168.0.184:58441?rtcpport=58569&localrtcpport=58569&pkt_size=1378

Any ideas?

**Comment by marcoraddatz** [comment]
Sorry, got no idea.

**Comment by oynek** [comment]
Got exactly the same problem. 

See: http://github.com/KhaosT/homebridge-camera-ffmpeg/issues/120

**Comment by marcoraddatz** [comment]
Closing this issue. Seem to be invalid settings.
