### ISSUE TITLE
After update to DSM 6.2 beta, the home APP can't pair with homebridge.

### ISSUE THREAD

**Issue by Fetiz** [marcoraddatz/homebridge-docker#34]
Just tried DSM 6.2 beta and reset up homebridge. After all the docker homebridge setting up, home app in iOS 11 can't find homebridge. 

![capture](https://user-images.githubusercontent.com/20578132/32112568-31b101a2-bb70-11e7-8569-87e3b29cbff3.PNG)
Homebridge has been set up properly.

I tried to change the name and the port of homebridge, still doesn't work.

**Comment by marcoraddatz** [comment]
Sorry, I cannot help you right now – won't upgrade DSM until 6.2 final. Will check it out later.

**Comment by evianzhow** [comment]
Even with latest stable version of DSM (6.1.x I assume), it doesn't work. While my old Xpenology DSM 6.0.2 works like a charm.

**Comment by Fetiz** [comment]
Please check the bonjour service isn't enable. Bonjour service use the same
ports as homebridge.

**Comment by yubiao** [comment]
I am experiencing the same problem after upgraded the docker package in Synology DSM to . DSM is running 6.1.4 though.

**Comment by leafney** [comment]
I get the same problem but maybe i solved it .
My Synology DSM is 6.1.4 and docker version is the lastest 17.05.0-0349.The bonjour service is stop.
My Iphone is 11.1.1  can not found homebridge, but my Ipad which is 11.1.2 works very well.
And then I upgraded the IPhone version to 11.1.2 and search the homebridge again, yes! now it works.

**Comment by Casao** [comment]
@Leafney Thanks for the heads up, 11.1.2 absolutely fixes the issue for me

**Comment by marcoraddatz** [comment]
Thanks for the updates with 11.1.2!

**Comment by Crady123** [comment]
I am having the same proble, with iOS 11.2 now... any clue?

**Comment by Fetiz** [comment]
@Crady123 As I said before, pls check your DSM setting. If the Bonjour service is turning on, close it.

**Comment by Crady123** [comment]
@Fetiz Thank you, I have read this yesterday and turnes off Bonjour yesterday - but no change... my iphones / ipad still do not find my homebridge.

btw... only Bonjour for printer was activated - but also it was working with activated Bonjour for months... and I did not change any settings - however it is deactivated now.
