### ISSUE TITLE
Home App does not find my homebridge anymore

### ISSUE THREAD

**Issue by Crady123** [marcoraddatz/homebridge-docker#38]
Hi there,

frist my Homebridge was running on a Raspberry Pi2 - but I had a lot of stability problems.
So I installed your Hombridge docker container on my Synology and it really worked perfectly!

But since a few days my home app (2 iPhones an 1 iPad) does not find my homebridge any more... Any clue why?

Is there a known problem with iOS 11.2?
Or is there a known problem with the new DSM 6.1.4-15217 Update 2 from November 2017?

How can I see if I am running the latest version of your hombebridge-docker?
I have chosen "latest" for downloading - but this was weeks (or months) ago. Does the docker container update itself? or do I have to update it manually? How?

Thank you?

**Comment by marcoraddatz** [comment]
`latest` only updates the package when booting. Can you restart the container and force an update?

**Comment by Crady123** [comment]
Oh... you meant the whole container does update itselt on reboot? Well I have rebooted it several times after having these problems.. so it should have been the latest vereion already.

Anyway... I have exportet the container settings, then I have deleted the container and have downloaded it again and have imported the settings again.

But no change... My iPhones and iPad still do not find the homebridge anymore... 
I also tried to add a new device - but even there the homebridge is not visible.

**Comment by sicaboy** [comment]
+1

**Comment by sicaboy** [comment]
You gotta disable the built-in Bonjour service in Synology system settings.

**Comment by Crady123** [comment]
Well homebridge worked perfectly with activated bonjour service in past...

But now I am having problems.

So now I have disabled the bonjour service but it still does not work.
Even updating my iPhone and AppleTV 4 (homekit fix) does not work.

What else can I do?

**Comment by Crady123** [comment]
ok... deleting my home in the home app, then stopping the container, deleting the presist folder and the starting container did the trick!

now it works... - even withe (re)activated bonjour
