### ISSUE TITLE
Install ffmpeg

### ISSUE THREAD

**Issue by benzman81** [marcoraddatz/homebridge-docker#4]
To use homebridge-camera-ffmpeg I need ffmpeg on the image. Could you pre-install it?
The following lines where neded:

`echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list`

`apt-get update`

`apt-get -y install ffmpeg`

Tried it in the install.sh, but somehow it didn't work.

**Comment by marcoraddatz** [comment]
I wanted to keep the image as slim as possible, that's why I removed all unused parts. Have you tried to install it via `install.sh` or via DSM terminal?

**Comment by benzman81** [comment]
Yeah, the install.sh didnt work with lines above. Maybe beause executed as separate SH script. Using a terminal on the docker image the lines above work.

**Comment by marcoraddatz** [comment]
Thank you. Exactly what I expected and you were right :) 

Can you try it again (newest develop build, some minutes ago)? The script now gets executed as root, so I was able to install all dependencies via `install.sh`.

**Comment by benzman81** [comment]
Almost same errors:

Updating Homebridge.
/root/.homebridge/package.json not found.
Installing plugins from /root/.homebridge/install.sh.
E: Invalid operation update
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ffmpeg

**Comment by marcoraddatz** [comment]
I'm sorry, I cannot reproduce this error. Following code worked for me:

```
#!/bin/bash

whoami
echo 'deb http://ftp.uk.debian.org/debian jessie-backports main' >> /etc/apt/sources.list
apt-get update
apt-get -y install ffmpeg
ffmpeg
```

"root" is being printed and `ffmpeg` can be called: "ffmpeg version 3.2.2-1~bpo8+1 Copyright (c) 2000-2016 the FFmpeg developers".

Possible error: Is the `install.sh` called via bash and also uses a bash shebang? I updated this some hours ago and it might not have been obvious.

**Comment by benzman81** [comment]
I doublecheck.

**Comment by benzman81** [comment]
Seems to be an encoding issue. Since I create and edit the file via windows shared folder, the line endings have been wrong. Converted to unix and now it seems to work.

**Comment by benzman81** [comment]
Just a side note. Since installing ffmpeg on every start takes pretty long I decided to fork your repo and add the code to the dockerfile to save start time ;-)

**Comment by marcoraddatz** [comment]
I'm curious: Why do you restart it that often? For development?

**Comment by benzman81** [comment]
Mostly for development or if I want to test plugins. And every night it restarts, too.
