### ISSUE TITLE
Build for Raspberry Pi

### ISSUE THREAD

**Issue by jswetzen** [marcoraddatz/homebridge-docker#41]
The README says the Docker image works for Raspberry Pi, but as far as I can see there’s only a build for the amd64 architecture. Do I have to build my own to get it going on an ARM device or did I miss something?

**Comment by marcoraddatz** [comment]
I'm sorry, don't have a Pi to test, but people told me that they used this package with a Pi and installed Docker before. If you make it work, please tell me how you did it and I'll add it to the docs.
