### ISSUE TITLE
No Response when away from home

### ISSUE THREAD

**Issue by FrothyDog** [marcoraddatz/homebridge-docker#43]
I have an issue where my homebridge devices show "no response" when I am away from the house (using an Apple TV as a resident HomeKit hub). Any ideas why this happens?

**Comment by marcoraddatz** [comment]
Do you use a Hue package?

**Comment by FrothyDog** [comment]
No, I am running this on a Synology NAS and only using the harmony (Logitech) homebridge package.

**Comment by FrothyDog** [comment]
Someone on another forum suggested it may be a Location services issue on my iPhone. Turns out that I had to enable "Share My Location" under Settings -> Privacy -> Location Services. That did the trick!
