### ISSUE TITLE
Homebridge_OPTS=-I

### ISSUE THREAD

**Issue by DocUltra** [marcoraddatz/homebridge-docker#48]
Hi 

I would like to install the below plugin, but I have to start homebridge in the insecure mode

https://www.npmjs.com/package/homebridge-alexa

but i cannot find the file homebridge in the folder /etc/default?
I search the homebridge.services?

**Comment by marcoraddatz** [comment]
I don't know which file you are searching? You can easily start an insecure Homebridge via `production-insecure` setting in the `.env` file. See https://github.com/marcoraddatz/homebridge-docker#plugin-development
