### ISSUE TITLE
Homebridge Version Upgrade?

### ISSUE THREAD

**Issue by RaGuKro** [marcoraddatz/homebridge-docker#49]
Hi!
I am using this good working docker image, but

I can´t install the homebrige-telegram plugin, because the plugin reports, that the homebrige Version (0.4.33) is too old, 0,4.35 is needed, the latest version is 0.4.38.

Is there an possibility for an update?

**Comment by deadbone** [comment]
Hi,
Yes, you can specify the version in the .env file
https://github.com/marcoraddatz/homebridge-docker/blob/master/samples/.env
