### ISSUE TITLE
log file flooded with temp readings  after docker upgrade 17.05.0-370

### ISSUE THREAD

**Issue by GravityRZ** [marcoraddatz/homebridge-docker#50]
Hello,

upgrade docker to the latest version yesterday.
Now the log is flooded with entries coming from 2 domoticz z-wave devices(probably through MQTT)
used RAM is growing

i was running homebridge v4.2 fine but think it is now running the latest version
is this new functionality

also when running 4.2 38MB of ram is consumed(HOMEBRIDGE_VERSION=0.4.32 is in the .ENV)
when running the latest version 68MB of ram is consumed(#HOMEBRIDGE_VERSION=0.4.32 is in the .ENV)

![image](https://user-images.githubusercontent.com/16853535/37873199-738d7aee-3017-11e8-854d-13fdb1c9eb0c.png)

**Comment by marcoraddatz** [comment]
Hey, I cannot reproduce this one. Maybe the plugin got updated through the upgrade and has increased logs?

**Comment by GravityRZ** [comment]
Yes, i think so.
i installed an old homebridge version and it is still the same.
Mem usage however has dropped so this was a temp thnig(probably caused by downloading updates during the install)

thanks
