### ISSUE TITLE
SFTP ?  

### ISSUE THREAD

**Issue by simonlanemusic** [marcoraddatz/homebridge-docker#51]
David,

I'm a noob on a mac how do do what you said below?  Lets pretend my network settings for the container is at 192.168.1.35

Once the container is up, SFTP your homebridge files into the shared folder (Step 5), and restart the 
container via the Container Station WebUI, and watch the console until the QR Code appears.

    install.sh
    config.json

**Comment by marcoraddatz** [comment]
Ticket seems to be unrelated here and might belong to another issue.
