### ISSUE TITLE
how do i know what ports to forward before running the container?

### ISSUE THREAD

**Issue by AdySan** [marcoraddatz/homebridge-docker#52]
I have two platforms in my config.json file. On running the container I see something like this

```
[2018-6-26 15:59:59] Homebridge is running on port 51826.
[2018-6-26 15:59:59] Camera Name is running on port 34575.
```

How do I know what port the camera is going to run on? I dont think there in a way to port forward on an existing container, is there?

**Comment by marcoraddatz** [comment]
If you can't force a specific port for the camera in the `config.json`, I don't see a way to bind a port permanently.
