### ISSUE TITLE
Homebridge Log

### ISSUE THREAD

**Issue by flipse27** [marcoraddatz/homebridge-docker#58]
Hello,
I'm new at using homebridge but I like your work very much. Everything is working fine. The console gives me the output of the log, but there are no log files of home bridge, I can use for homebridge-server or Homebridge-config-ui-x. 
When starting homebridge with parameter to write homebridge.log, there is no more output in the docker console.
what am I doing wrong?

**Comment by marcoraddatz** [comment]
I'm sorry, didn't spend much time with the logs. There's an open issue (#9) about implementing a better logging, but unfortunately nobody did it so far.
