### ISSUE TITLE
Doesn't not work with VPN - help

### ISSUE THREAD

**Issue by jameswill377** [marcoraddatz/homebridge-docker#6]
Hello

Homebridge through docker works really well on my Synology. However, as soon as I turn on the vpn on my Synology, homebridge stops working. 

is there any way around it where I can use vpn and also have homebridge working?

Any help will be appreciated.

thanks again to Marco for making this docker image. KUDOS :)

**Comment by marcoraddatz** [comment]
Does the container crash or is it the connection? Also, do you mean the Synology VPN package or a connection to another server (f.e. router)?

**Comment by jameswill377** [comment]
The container doesn't crash. I think its just the connection. So basically, I have setup PrivateInternetAccess VPN on Synology. As soon as I activate this VPN, I can no response error on my iPhone. 

I'm assuming that this container doesn't work over VPN but I don't know for sure.

Can anyone also try to see if there are any issues with VPN and this container. I know someone else commented on the Marco's blog in regards to the VPN issue.

Btw, im not very tech savvy when it comes to issues like  this.

**Comment by xantalor** [comment]
Normally the vpn and homebridge should not collide. (Port POV)

**Comment by jameswill377** [comment]
i think because the container uses the default connection, it would fall under the vpn as as soon as you activate the vpn, all connections from synology go through the vpn

Is there any other way around it where we can tell docker not to go through vpn or any other way ?

**Comment by marcoraddatz** [comment]
What happens, if you change the connection settings? Esp. the second one?

![bildschirmfoto 2017-01-30 um 10 59 11](https://cloud.githubusercontent.com/assets/248815/22418907/52009f68-e6db-11e6-8bdc-c3b642c69e9c.png)

**Comment by jameswill377** [comment]
Hello 

thanks Marco. I really appreciate your assistance in resolving this. 

I haven't enabled the second option. please see my VPN Setting below:
<img width="622" alt="screenshot" src="https://cloud.githubusercontent.com/assets/22332233/22419082/e7afd688-e72f-11e6-971a-bb03c05b79b6.png">

My docker related network settings are:
<img width="1136" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/22332233/22419211/868b2b0e-e730-11e6-8335-80c16b1903e8.png">

Your feedback welcome.

**Comment by jameswill377** [comment]
Update: Enabling the second option - "allow other network devices..." does not resolve the issue,

**Comment by marcoraddatz** [comment]
Closed this because of its age. Please verify that you don't use IPv6!
