### ISSUE TITLE
Issue with new CCU Update 3.41.11

### ISSUE THREAD

**Issue by Larson-Sei180LX** [marcoraddatz/homebridge-docker#62]
Hey there, sorry for my bad english.

There is an issue running homebridge with the new version of raspmatic 3.41.11.  Fresh installation along ur instruction can only find the bridge and devices in ios. But when u want to switch on and off a device u can only see the status "actualising" and nothing else is happening. later on u can read not reachable. There is a workarround for changing that file HomeMaticRPC.js (https://homematic-forum.de/forum/viewtopic.php?f=41&p=468276&sid=2a4118f718068bb76fd3d1097c84e582#p468276) but i dont know how to do that. 

is it possible to change it in dockers-Container gerneraly? With an update? Dont know how to fix that issue there...
Thank u

**Comment by DanielWeeber** [comment]
You've mapped the container contents to a directory outside of the container itself (esp. /volume1/docker/homebridge/). There you can find the files of your modules (and everything else from the docker container).

As this commit you mentioned is included in the development brach you can just switch to that.
Change the npm install command in the install.sh file to
"npm install git+https://github.com/thkl/homebridge-homematic/tree/develop"

This is not an issue and should be closed.
