### ISSUE TITLE
Problems with my first homebridge

### ISSUE THREAD

**Issue by sciuk** [marcoraddatz/homebridge-docker#63]
It doesnt work but i dont know what to do. Would you please be so kind and help me out.
I installed the homebridge and the install and config files. And thats what i got:

[1/14/2019, 6:00:03 PM] Homebridge is running on port 44749.
/root/.homebridge/.env not found.
Default env variables will be used.
/root/.homebridge/package.json not found.
/root/.homebridge/install.sh not found.
[1/14/2019, 7:59:15 PM] config.json (/root/.homebridge/config.json) not found.
[1/14/2019, 7:59:15 PM] No plugins found. See the README for information on installing plugins.

Seems like a path problem to me? I installed homebridge on „public/homebridge on my qnap

**Comment by marcoraddatz** [comment]
Seems like the env and config files cannot be found. Thus the settings (f.e. port) are invalid: https://github.com/marcoraddatz/homebridge-docker/wiki/Installation-via-Synology-DSM#2-prepare-your-scripts
