### ISSUE TITLE
Failed to restart homebridge using homebridge-config-ui-x

### ISSUE THREAD

**Issue by Nappyy** [marcoraddatz/homebridge-docker#67]
Hi there,

I've installed the "homebridge-config-ui-x" plugin.
If I try to restart homebridge service using plugin default setting "sudo -n systemctl restart homebridge" it fails.
What's to correct command to restart homebridge in qnap docker container?

kind regards,
Kai

**Comment by deadbone** [comment]
I don't know qnap, but I think you should restart the whole docker container which contains your homebrige's image. Hope it's help a bit.

**Comment by Nappyy** [comment]
well, I guess this is a bit overpowered if you just want to update your config.json in the webinterface.

**Comment by deadbone** [comment]
yep but on my Synology I always do like this :) But I think you could give it a try and after that I think config UI give you the hability to refresh your config

**Comment by Nappyy** [comment]
yes, config UI gives the ability to refresh your config.
but to apply the new settings, homebridge need to restart.
usually you would now just restart the homebridge service, but this is not possible in docker container (at least not using systemctl command).

So there are two viable options:
a) find another (proper) terminal command to restart homebridge service in docker
b) restart docker container using terminal command (don't know if this is possible)

the clean way would be to restart just the service...

**Comment by deadbone** [comment]
I just test on my Synology this command : 

sudo /usr/local/bin/docker start homebridge 

It's working (my container is obviously named "home bridge" :))

so I think you could adapt this command to your qnap

(there are stop and restart options too)

**Comment by Nappyy** [comment]
I guess this would restart the container from host machines terminal, isn't it?
config UI is running inside the container, so this wouldn't work in my opinion :/

**Comment by deadbone** [comment]
It’s for your option b)

**Comment by Nappyy** [comment]
oh i see.
in option b) I still wanted to reboot the container from the container itself (the config UI), not the host machine
