### ISSUE TITLE
Homebridge update v0.4.50 needed

### ISSUE THREAD

**Issue by LeviJSmith** [marcoraddatz/homebridge-docker#68]
Greetings,

Any chance the docker image for synology could be updated to homebridge 0.4.50?  I need a newer version than what is currently packaged with this image in order to utilize the new homebridge-ring-alarm plugin.  If there are no near term plans to update the docker image with a newer version of homebridge, is it possible for me to update homebridge myself manually and how might I do that.

-Levi

**Comment by marcoraddatz** [comment]
https://github.com/marcoraddatz/homebridge-docker/wiki/Plugin-development#homebridge_version

**Comment by LeviJSmith** [comment]
That did the trick.  Thx so much.

**Comment by marcoraddatz** [comment]
Glad to hear! 👍
