### ISSUE TITLE
Homebridge crashes after a few days

### ISSUE THREAD

**Issue by jeGit** [marcoraddatz/homebridge-docker#69]
Hi, running your docker image on a Synology.
After the latest restart I figured out that Homebridge crashes after a couple of days with the following error message in the container's log viewer:

[1/4/2020, 5:28:18 PM] [ZWayServer] ERROR: Fatal! Authentication failed (error code 401)! Check the username and password in config.json! | stdout
-- | --
Config.json is OK according to the validator.
This error message is repeated several times before the crash.

Homebridge version is 0.4.50
Username and password have not been changed during this time.
Is there any more info available for a more precise analysis.
Tia, Jens

**Comment by marcoraddatz** [comment]
I don't know the Z-Way plugin. Have you checked your firewall?

However, I guess this error is not related to this project, but might be related to this one here: https://github.com/SphtKr/homebridge-zway/blob/master/index.js#L185
