### ISSUE TITLE
Stuck at "Add Accessory" in Home App

### ISSUE THREAD

**Issue by maelstromchanneled** [marcoraddatz/homebridge-docker#72]
Hi, I installed homebridge on my QNAP a few days ago and have been spending many hours trying to get it to work.  I've added a plug-in and verified that it is loading and communicating with my device (MyQ garage door sensors), and the accessory even shows up in Home App under manual add.  But, I cannot get the Home App to connect to the homebridge.  Could someone please help me?

Below are the details:

- Followed the tutorial in the wiki under GUI Examples > QNAP
- Verified in console that container instance ran successfully
- Stopped container

- Added install.sh file:

> #!/bin/bash
> npm update -g n
> npm install -g homebridge-chamberlain
> npm install -g homebridge-myq2

- Added config.json file:

> {
>   "bridge": {
>     "name": "mybridgename",
>     "username": "CC:22:3D:E3:CE:30",
>     "port": 51826,
>     "pin": "123-45-678"
>   },
>   "description": "This file configures support for Nest, TP-Link Devices and HarmonyHub Remote.",
>   "platforms": [
>     {
>       "platform": "MyQ2",
>       "email": "mymyqemailaddress",
>       "password": "mymyqpassword"
>     }
>   ],
>   "accessories": [
>   ]
> }
> 

- Relaunched container
- Verified in console that it started up correctly
- Got the QR code and accessory code
- Also received confirmation that homebridge-myq2 had discovered garage doors:

> [2020-4-22 08:14:23] Homebridge is running on port 51826.                                                                                                                                                                             
> [2020-4-22 08:14:25] [MyQ2] Initializing platform accessory 'Main Garage Door (ID: snip)'...                                                                                                                                    
> [2020-4-22 08:14:25] [MyQ2] Initializing platform accessory 'Side Garage Door (ID: snip)'...                                                                                                                                    

- Went into Home App and selected add accessory
- The homebridge accessory showed up under manually add option
- Selected the homebridge accessory
- Confirmed using uncertified accessory
- Entered manual code 12345678
- Waited a long time, final got error that the homebridge could not be added

**Comment by marcoraddatz** [comment]
Hey @blaflen,

Sorry to say, but I cannot help with this. It seems to be either a misconfiguration in the config files or an error in the MyQ2 plugin. Homebridge itself seems to be running without any issues:

> [2020-4-22 08:14:23] Homebridge is running on port 51826.

Good luck with it,
Marco

**Comment by maelstromchanneled** [comment]
Thanks @marcoraddatz - is there some limited build that is guaranteed to work that I can use to debug this?  The issue is that I can't connect with the Home app

**Comment by maelstromchanneled** [comment]
@marcoraddatz  - after several days of trial and error, I decided to go with the qnap console instructions.  Five minutes later, everything is up and running and connected in the Home app.  Previously, I was following the QNAP GUI instructions, and the main difference is the network configuration.  The GUI instructions say to put the container in bridge mode, and that doesn't work for me.  The console instructions start the container in host mode, and that is the only difference between the working and not working attempts.

**Comment by marcoraddatz** [comment]
Good to hear and thanks for sharing!

It's related to #73. I'll modify the wiki soon.
