### ISSUE TITLE
Feature request: update install instructions

### ISSUE THREAD

**Issue by maelstromchanneled** [marcoraddatz/homebridge-docker#74]
I spent the last several days with trial and error following the QNAP GUI instructions.  I could get the Homebridge to come up, and I could even see it in the Home App, but I could not get the Home App to connect the Homebridge accessory.

I decided to try the QNAP console instructions.  Five minutes later, everything is up and running and the accessory is connected in the Home app.

I checked the two QNAP containers and the only difference I could find is the network configuration.  The GUI instructions say to put the container in bridge mode, and that doesn't work for me.  The console instructions start the container in host mode, and that is the only difference between the working and not working attempts.

Please either

- update the GUI instructions to suggest experimenting with network configs (bridge vs. host)
- add a comment to the GUI instructions suggesting people try the console approach if they encounter Home APP connectivity issues

**Comment by marcoraddatz** [comment]
I added the info you suggested.

Thanks for feedback!
