### ISSUE TITLE
Accessories show "No response" after updating

### ISSUE THREAD

**Issue by calvinandhobbes** [marcoraddatz/homebridge-docker#75]
Had the image running successfully without issues for months on a QNAP with 2 plugins (homebridge-tplink-smarthome & homebridge-daikin-local)

Now seeing "No response" for all accessories when opening the HomeKit app.
Most devices still work when clicking once on the icon - but "No response" after every update.

Tried to 
- remove and re-add Homebridge in the app
- completely re-install the Homebridge docker image (including removal of all cache files)

No success. And no visible error messages in the console..

Tried same config with a macOS installation of Homebridge - works fine.

**Comment by marcoraddatz** [comment]
Have you had the mac and Docker version running simultaneously?

**Comment by calvinandhobbes** [comment]
No - only tried it on the Mac after I started having issues..

**Comment by marcoraddatz** [comment]
What's the Homebridge version you are using? I had problems with Homebridge v1 and the node version which have been solved in the develop branch.

**Comment by calvinandhobbes** [comment]
1.0.4

**Comment by marcoraddatz** [comment]
It might relate to the node version. V5 might solve this. Could you please try?

**Comment by calvinandhobbes** [comment]
Deleted the old image and installed the new version. Issue seemed to still be present at first after adding Homebridge to HomeKit, but does work now without the issue. Thanks a lot.
