### ISSUE TITLE
Using apt-get upgrade

### ISSUE THREAD

**Issue by thomasvt1** [marcoraddatz/homebridge-docker#8]
Looking at the best practices for a Docker container, the use of `apt-get upgrade` is not recommended

Source: [https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/](url)

**Comment by marcoraddatz** [comment]
Thanks Thomas, will be removed in a future update.

**Comment by thomasvt1** [comment]
No problem :)

**Comment by marcoraddatz** [comment]
Changes have been pushed to the master. Thanks again!
